### PR TITLE
Update sites.ad

### PR DESCRIPTION
**Pull request by luistrigueiros**
Two example project, with: Spring Boot Gradle, Travis CI, Openshift 2,x deploy

### CODE REVIEW

**Comment by luistrigueiros** [comment]
Two example project, with: Spring Boot Gradle, Travis CI, Openshift 2,x deploy

**Comment by jonbullock** [comment]
Any reason why you've closed this PR?

**Comment by luistrigueiros** [comment]
I am sorry this is my first pull request so I don't know very well how to
use it I can make a new one.

**Comment by jonbullock** [comment]
No problem I'll re-open this and merge it.

**Pull request merged**
